# fly.toml generated for Spooky Race static site on Fly.io
# Replace the 'app' name after running `flyctl launch` if needed.
app = "spooky-race-2025"  # change after `flyctl launch`
primary_region = "syd"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
